---
title: "Homework1"
output: html_notebook
---

HW1 Assignments . 
P.S:- Question#1 is attended at the end  

```{r LogGamma Loop}
log_gamma_loop = function(n) {
  
  sum = 0
  if (n == 1){
    return(0)
  }
  for (i in 1:(n-1)){
    sum = sum + log(i)
  }
  sum
}

print(log_gamma_loop(5))
```

```{r}

```

```{r Recursive LogGamma}
log_gamma_recursive = function(n) {
  if (n == 1) {
    return(0)
  } else {
    x = n-1
    log((x)) + log_gamma_recursive(n-1)
  }
  
}
print(log_gamma_recursive(5))
```
```{r}

```

```{r Sum of LogGamma}
sum_log_gamma_loop = function(n) {
  sum_log = 0
  for (i in 1:n){
    
    x = log_gamma_loop(i)
    
    sum_log = sum_log + x
    
  }
  sum_log
}

sum_log_gamma_recursive = function(n) {
  sum_rec = 0
  for(i in 1:n) {
    rec_call = log_gamma_recursive(i)
    sum_rec = sum_rec + rec_call
  }
  sum_rec
}

sum_lgamma = function(n) {
  sum_lgamma = 0
  for (i in 1:n){
    sum_lgamma = sum_lgamma + lgamma(i)
  }
  sum_lgamma
}


```

```{r Create DF to plot}
# Create a DF and add observations to plot
loop_through = 1000
step_through = 50

run.time.vector = function(Func){
  sum_time = vector(mode="numeric", length=0); # holds the runtime of the results
  for (elem in seq(1,loop_through,by=step_through)){
    l = system.time(Func(elem))[[1]]
    sum_time = c(sum_time,l)
  }
  return(sum_time) 
}

log_gamma_loop_time <- run.time.vector(sum_log_gamma_loop)
log_gamma_recursive_time <- run.time.vector(sum_log_gamma_recursive)
log_gamma_time <- run.time.vector(sum_lgamma)

run.time.df <- data.frame(log_gamma_loop_time,log_gamma_recursive_time,log_gamma_time)

size <- seq(1,loop_through,by=step_through)
run.time.df <- cbind(run.time.df,size)

```

```{r Plot Observation}
plotfunc = function(df){
  require(ggplot2)
  ggplot(df, aes(size)) + geom_line(aes(y = log_gamma_loop_time, colour = "log_gamma_loop_time")) + geom_line(aes(y = log_gamma_recursive_time, colour = "log_gamma_recursive_time"))+geom_line(aes(y = log_gamma_time, colour = "log_gamma_time"))+ labs(x="size",y="time(s)") 
}

plotfunc(run.time.df)
```

```{r Problem 1 - Observation of R}
print(factorial(5))
system.time(factorial(5))

manual_fact = function(n) {
  sum_fact = 1
  for (i_fact in 1:n){
    sum_fact = sum_fact * i_fact
    }
  return(sum_fact)
  }
system.time(print(manual_fact(12)))

```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).
